spring.application.name=hackathon-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/hackathon_db
spring.datasource.username=nishithakrishna
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

server.port=8080

spring.sql.init.mode=never

jwt.secret=HackathonMgmtSystemSecretKeyForJWT2024MustBe256BitsLong!!
jwt.expiration=86400000
